# Generated by Django 4.1.7 on 2023-02-24 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="data_de_nascimento",
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
