# Generated by Django 4.1.7 on 2023-02-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_cliente_data_de_nascimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                default="example@email.com", max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
